name: rubyci-android
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 * * * *'
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: zsh setup-android.sh 29 x86_64 30000
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
